server:
  port: 443
  ssl:
    bundle: incredy-gateway
    enabled-protocols: TLSv1.3

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: incredy
          uri: lb://incredy
          predicates:
          - Path=/incredy/**
          filters:
          - StripPrefix=1
  ssl:
    bundle:
      jks:
        incredy-gateway:
          key:
            alias: incredy-gateway
          keystore:
            location: classpath:incredy-gateway-keystore.p12
            type: PKCS12
            password: password
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  server:
    port: 9080
  health:
    defaults:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "info,health,metrics"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log
    max-history: 30
    max-size: 10MB   
  level:
    org.springframework.cloud.gateway: INFO
    fr.bgsoft: INFO